# retip - ReXGlue Codegen Configuration

includes = [
"config/retip_crt.toml",
"config/retip_ctx_ctr.toml",
"config/retip_functions.toml",
"config/retip_midasm.toml",
"config/retip_hooked.toml"
]

project_name = "retip"
file_path = "assets/default.xex"
out_directory_path = "generated"

setjmp_address = 0x82AE2EA0
longjmp_address = 0x82AE2A60