# Per-shader settings.
# Format: <ucode_hash_hex> = { name = "<name>", disabled = <bool> }
1c98c5fa29538181 = { name = "LongGrass_ps", disabled = false }
1e6883fccde1f688 = { name = "WithoutWaterNormal_vs", disabled = false }
3fd806422efd3aa1 = { name = "WaterShader_ps", disabled = false }
4d4708c3440b276d = { name = "WaterOnScreen_ps", disabled = false }
4f1712ffc87e1192 = { name = "WaterShader_vs", disabled = false }
60caa57a8a53985e = { name = "BackgroundSprites_vs", disabled = false }
6c4d7159da895b70 = { name = "Dirt_ps", disabled = false }
6c8d5adf0cdd54bb = { name = "PlayerLight_ps", disabled = false }
6e6f29256dee8039 = { name = "GroundIce_ps", disabled = false }
8a9ef0085a086623 = { name = "BackgroundProps_vs", disabled = false }
8eb70647b4b1f276 = { name = "grass_vs", disabled = false }
9c02c5e187b6c4ed = { name = "PesterFaceOnBarral_ps", disabled = false }
e496143779662ce2 = { name = "Sky_ps", disabled = false }
