/**
******************************************************************************
* ReTiP: Viva Pinata Recompiled                                              *
******************************************************************************
* Copyright (c) 2026 SolarCookies. Licensed under custom noncommercial terms.
*
* This software is licensed for non-commercial, private, and educational use 
* only. You may modify, rewrite, and optimize this code provided that full 
* attribution is given to the original authors listed on the project repository. 
* Commercial use is prohibited.
******************************************************************************
*/

#include "CvarMenu.h"

#include <algorithm>
#include <cstdio>
#include <cstring>

namespace {

constexpr size_t kTextBufferSize = 256;

ImColor ColorForCategory(const std::string& category) {
    uint32_t hash = 2166136261u;
    for (char c : category) {
        hash = (hash ^ static_cast<uint8_t>(c)) * 16777619u;
    }
    return ImColor::HSV((hash % 360) / 360.0f, 0.55f, 0.95f);
}

bool IsIntegerType(rex::cvar::FlagType type) {
    switch (type) {
        case rex::cvar::FlagType::Int32:
        case rex::cvar::FlagType::Int64:
        case rex::cvar::FlagType::Uint32:
        case rex::cvar::FlagType::Uint64:
            return true;
        default:
            return false;
    }
}

std::string DoubleToString(double value) {
    char buf[64];
    snprintf(buf, sizeof(buf), "%.9g", value);
    return buf;
}

}

CvarMenuPage::CvarMenuPage(std::string category) {
    cvarCategory = std::move(category);
    autoGenerated = true;

    const size_t slash = cvarCategory.find('/');
    name = (slash == std::string::npos) ? cvarCategory : cvarCategory.substr(slash + 1);
    description = "Options registered under " + cvarCategory;
    color = ColorForCategory(cvarCategory);
}

void CvarMenuPage::OnOpen() {
    focusIndex_ = 0;
    RefreshRows();
}

void CvarMenuPage::RefreshRows() {
    const auto& registry = rex::cvar::GetRegistry();
    registrySize_ = registry.size();

    rows_.clear();
    for (const auto& entry : registry) {
        if (entry.category != cvarCategory || entry.is_debug_only) continue;

        Row row;
        row.name = entry.name;
        row.label = entry.description.empty() ? entry.name : entry.description;
        if (entry.lifecycle == rex::cvar::Lifecycle::kRequiresRestart) {
            row.label += " (restart)";
        }
        rows_.push_back(std::move(row));
    }

    rowAccel_.assign(rows_.size(), TiPWidgets::AccelState{});
    rowHold_.assign(rows_.size(), 0.0f);
    rowAccum_.assign(rows_.size(), 0.0f);
    textBuffers_.assign(rows_.size(), std::vector<char>(kTextBufferSize, '\0'));
    textActive_.assign(rows_.size(), 0);

    if (focusIndex_ >= static_cast<int>(rows_.size())) {
        focusIndex_ = rows_.empty() ? 0 : static_cast<int>(rows_.size()) - 1;
    }
}

bool CvarMenuPage::DrawRow(size_t index, const rex::cvar::FlagEntry& info, bool focused,
                           float width, const TiPWidgets::ListInput& input) {
    const Row& row = rows_[index];
    const char* label = row.label.c_str();
    const auto& constraints = info.constraints;

    if (constraints.HasAllowedValues()) {
        const auto& values = constraints.allowed_values;
        std::vector<const char*> options;
        options.reserve(values.size());
        for (const auto& v : values) options.push_back(v.c_str());

        const std::string current = rex::cvar::GetFlagByName(info.name);
        auto it = std::find(values.begin(), values.end(), current);
        int selected = (it == values.end()) ? 0 : static_cast<int>(it - values.begin());

        if (TiPWidgets::Cycler(label, selected, options.data(), static_cast<int>(options.size()),
                               focused, width, input)) {
            rex::cvar::SetFlagByName(info.name, values[selected]);
            return true;
        }
        return false;
    }

    switch (info.type) {
        case rex::cvar::FlagType::Boolean: {
            bool value = rex::cvar::Query<bool>(info.name);
            if (TiPWidgets::Toggle(label, value, focused, width, input)) {
                rex::cvar::SetFlagByName(info.name, value ? "true" : "false");
                return true;
            }
            return false;
        }

        case rex::cvar::FlagType::Command: {
            if (TiPWidgets::ListButton(label, focused, false, width) ||
                (focused && input.confirm)) {
                rex::cvar::InvokeCommand(info.name, "");
                TiPWidgets::SetInputCooldown(0.25f);
                return true;
            }
            return false;
        }

        case rex::cvar::FlagType::String: {
            auto& buffer = textBuffers_[index];
            if (!textActive_[index]) {
                const std::string current = rex::cvar::GetFlagByName(info.name);
                std::snprintf(buffer.data(), buffer.size(), "%s", current.c_str());
            }
            ImGui::TextUnformatted(label);
            TiPWidgets::FocusBar(focused, ImGui::GetFrameHeight());
            char id[128];
            std::snprintf(id, sizeof(id), "##%s", info.name.c_str());
            ImGui::SetNextItemWidth(width);
            const bool committed = ImGui::InputText(id, buffer.data(), buffer.size(),
                                                    ImGuiInputTextFlags_EnterReturnsTrue);
            textActive_[index] = ImGui::IsItemActive() ? 1 : 0;
            if (committed) {
                rex::cvar::SetFlagByName(info.name, buffer.data());
                return true;
            }
            return false;
        }

        case rex::cvar::FlagType::Double: {
            float value = static_cast<float>(rex::cvar::Query<double>(info.name));
            bool changed = false;
            if (constraints.HasRangeConstraint()) {
                const float lo = static_cast<float>(constraints.min.value_or(0.0));
                const float hi = static_cast<float>(constraints.max.value_or(1.0));
                const float step = (hi - lo) / 100.0f;
                changed = TiPWidgets::FloatSlider(label, value, lo, hi, step, focused, width,
                                                  rowHold_[index], rowAccum_[index]);
            } else {
                changed = TiPWidgets::FloatStepper(label, value, 0.1f, focused, width,
                                                   rowAccel_[index]);
            }
            if (changed) {
                rex::cvar::SetFlagByName(info.name, DoubleToString(value));
            }
            return changed;
        }

        default:
            break;
    }

    if (!IsIntegerType(info.type)) {
        return false;
    }

    if (info.is_color) {
        const auto packed = static_cast<uint32_t>(rex::cvar::Query<int64_t>(info.name));
        uint8_t r = 0, g = 0, b = 0, a = 0;
        rex::cvar::UnpackColor(packed, info.color_format, r, g, b, a);
        float rgba[4] = {r / 255.0f, g / 255.0f, b / 255.0f, a / 255.0f};

        ImGui::TextUnformatted(label);
        TiPWidgets::FocusBar(focused, ImGui::GetFrameHeight());
        char id[128];
        std::snprintf(id, sizeof(id), "##%s", info.name.c_str());
        ImGui::SetNextItemWidth(width);
        if (ImGui::ColorEdit4(id, rgba, ImGuiColorEditFlags_AlphaBar)) {
            const uint32_t repacked = rex::cvar::PackColor(
                static_cast<uint8_t>(rgba[0] * 255.0f), static_cast<uint8_t>(rgba[1] * 255.0f),
                static_cast<uint8_t>(rgba[2] * 255.0f), static_cast<uint8_t>(rgba[3] * 255.0f),
                info.color_format);
            rex::cvar::SetFlagByName(info.name,
                                     std::to_string(static_cast<int32_t>(repacked)));
            return true;
        }
        return false;
    }

    int value = static_cast<int>(rex::cvar::Query<int64_t>(info.name));
    bool changed = false;
    if (constraints.HasRangeConstraint()) {
        const int lo = static_cast<int>(constraints.min.value_or(0.0));
        const int hi = static_cast<int>(constraints.max.value_or(0.0));
        changed = TiPWidgets::IntSlider(label, value, lo, hi, focused, width, rowAccel_[index]);
    } else {
        changed = TiPWidgets::IntStepper(label, value, 1, focused, width, rowAccel_[index]);
    }
    if (changed) {
        rex::cvar::SetFlagByName(info.name, std::to_string(value));
    }
    return changed;
}

void CvarMenuPage::OnDraw() {
    if (rex::cvar::GetRegistry().size() != registrySize_) {
        RefreshRows();
    }

    auto input = TiPWidgets::PollInput(inputTimer_, 0.18f);

    if (input.back) {
        wantsClose = true;
        return;
    }

    if (rows_.empty()) {
        ImGui::TextDisabled("No cvars registered under %s", cvarCategory.c_str());
        return;
    }

    int vertDir = TiPWidgets::GetHeldDir(SDL_GAMEPAD_BUTTON_DPAD_UP, SDL_GAMEPAD_BUTTON_DPAD_DOWN,
                                         ImGuiKey_UpArrow, ImGuiKey_DownArrow);
    focusIndex_ += TiPWidgets::AccelTick(vertAccel_, vertDir, 15.0f, 1.0f);
    TiPWidgets::WrapIndex(focusIndex_, static_cast<int>(rows_.size()));

    const float width = ImGui::GetContentRegionAvail().x;

    TiPWidgets::PushListStyle();
    for (size_t i = 0; i < rows_.size(); i++) {
        const rex::cvar::FlagEntry* info = rex::cvar::GetFlagInfo(rows_[i].name);
        if (!info) continue;

        DrawRow(i, *info, focusIndex_ == static_cast<int>(i), width, input);

        if (ImGui::IsItemHovered()) {
            focusIndex_ = static_cast<int>(i);
            ImGui::SetTooltip("%s", rows_[i].name.c_str());
        }
    }
    TiPWidgets::PopListStyle();
}
