#Contains all the functions that have working hooks

[functions]
0x824DC840 = {name = "rex_gardenBudgetGetIsTagAvailable_824DC840"}
0x821F0730 = {name = "rex_camMainGetAspectRatio_821F0730"}
0x821F07E0 = {name = "rex_camMainGetPos_821F07E0"}
0x821C8E78 = {name = "rex_appMainDraw_821C8E78"}
0x821C91C0 = {name = "rex_appMainTickPreDraw_821C91C0"}
#sub_822C1C00
0x822C1C00 = {name = "rex_inputPitchState_822C1C00"}
#sub_822C4260
0x822C4260 = {name = "rex_inputGetState_822C4260"}

#Rendering hooks (wireframe capture)
0x82664640 = {name = "rex_render_D3DDevice_BeginIndexedVertices_82664640"}
0x82664FF0 = {name = "rex_render_D3DDevice_DrawIndexedVertices_82664FF0"}
0x82658228 = {name = "rex_render_D3DDevice_SetIndices_82658228"}