/** 
******************************************************************************
* ReTiP: Viva Pinata Recompiled                                              *
******************************************************************************
* Copyright (c) 2026 SolarCookies. Licensed under custom noncommercial terms.
*
* This software is licensed for non-commercial, private, and educational use 
* only. You may modify, rewrite, and optimize this code provided that full 
* attribution is given to the original authors listed on the project repository. 
* Commercial use is prohibited.
*
* DISCLAIMER: This software is provided "as-is" without warranty of any kind. 
* This project is an unofficial fan translation layer and does NOT provide, 
* distribute, or package any copyrighted game assets, binaries, or media belonging 
* to Microsoft or Rare. Users must provide their own legally obtained game assets. 
* This software must not be used in any manner that violates Microsoft's copyrights.
* DO NOT REDISTRIBUTE GAME ASSETS OR PROMOTE PIRACY.
*
* AI USE GUIDELINES:
* This project is built with minimal AI usage. We may utilize basic inline code 
* suggestions or rely on AI assistance for debugging, but the vast majority of 
* this codebase is written by hand. We manually decompile functions,
* reverse engineer structs, and write hooks to ensure accuracy and maintainability.
*
* The core goal of ReTiP is not only to get the game running, but to 
* research, document, and learn exactly how the game operates under the hood so that 
* we can provide modding support. We do not support using AI for creative 
* task or problem solving. i.e asking an AI agent to "find a way to 
* make freecam work". Instead, AI should only be used for small, boilerplate tasks or
* parsing a 1000 line crash log to isolate an error. We actively encourage all project 
* contributors to avoid the use of AI agents entirely when writing code or decompiling functions.
*
* The truth of the matter is that AI when used currectly by people who understand the output
* can be incredibly useful just like intelisense, being able to press Tab to autocomplete a
* for loop can save time. However, AI is not a replacement for human understanding and
* should not be used to replace the process of learning and understanding how the game works.
*
* We strongly prefer the use of local models that do not harm the environment and 
* can run entirely on your own local hardware over cloud based AI services. Ultimately, 
* all pull requests and code contributions will be strictly reviewed by people who 
* understand the codebase and the game. If you list Claude or any other AI as a coauthor 
* or contributor, your PR will be rejected regardless of whether it works.
******************************************************************************
*/

#pragma once
#include <filesystem>
#include <utility>
#include <string>
#include <rex/ui/imgui_dialog.h>
#include <rex/ui/keybinds.h>
#include "imgui.h"
#include "SmartStyles.h"
#include "TiPWidgets.h"

class TipToolsPage {
public:
    virtual ~TipToolsPage() = default;
    std::string name;
    std::string description; // this is a tooltip when hovering with the mouse
    ImColor color = ImColor(255, 255, 255);
    bool wantsClose = false;
    std::string cvarCategory;
    bool autoGenerated = false;
    virtual void OnOpen() = 0;
    virtual void OnDraw() = 0;
    virtual void OnClose() = 0;
};

class TipToolsDialog : public rex::ui::ImGuiDialog {
public:
    bool visible_ = false;
    explicit TipToolsDialog(rex::ui::ImGuiDrawer* drawer, std::filesystem::path configPath)
        : rex::ui::ImGuiDialog(drawer), configPath_(std::move(configPath)) {
            rex::ui::RegisterBind("bind_tool_overlay", "F1", "Toggle Tools overlay", [this] {
            visible_ = !visible_;
            });
            rex::ui::RegisterBind("bind_upscaling_menu", "F11", "Toggle Upscaling menu", [this] {
            TogglePage("Upscaling");
            });
        }
        ~TipToolsDialog() {
        rex::ui::UnregisterBind("bind_tool_overlay");
        rex::ui::UnregisterBind("bind_upscaling_menu");
    }

    void TogglePage(const std::string& pageName) {
        int index = -1;
        for (size_t i = 0; i < pages.size(); i++) {
            if (pages[i]->name == pageName) {
                index = static_cast<int>(i);
                break;
            }
        }
        if (index < 0) return;
        if (visible_ && selectedPage == index) {
            pages[index]->OnClose();
            selectedPage = -1;
            visible_ = false;
            return;
        }
        if (selectedPage >= 0 && selectedPage < static_cast<int>(pages.size())) {
            pages[selectedPage]->OnClose();
        }
        visible_ = true;
        selectedPage = index;
        highlightedIndex = index;
        pages[index]->OnOpen();
    }

    void DrawMenu();
    void HandleInput();
    void SaveSettings();

    void SyncCvarPages();

    void OnDraw(ImGuiIO& io) override;

    std::vector<std::unique_ptr<TipToolsPage>> pages;
    int selectedPage = -1;
    int highlightedIndex = 0;
    float lastInputTime = 0.0f;
    TiPWidgets::AccelState vertAccel;
    std::filesystem::path configPath_;
    float lastSaveTime = -1.0f;
    size_t lastRegistrySize_ = 0;
};
