/** 
******************************************************************************
* ReTiP: Viva Pinata Recompiled                                              *
******************************************************************************
* Copyright (c) 2026 SolarCookies. Licensed under custom noncommercial terms.
*
* This software is licensed for non-commercial, private, and educational use 
* only. You may modify, rewrite, and optimize this code provided that full 
* attribution is given to the original authors listed on the project repository. 
* Commercial use is prohibited.
*
* DISCLAIMER: This software is provided "as-is" without warranty of any kind. 
* This project is an unofficial fan translation layer and does NOT provide, 
* distribute, or package any copyrighted game assets, binaries, or media belonging 
* to Microsoft or Rare. Users must provide their own legally obtained game assets. 
* This software must not be used in any manner that violates Microsoft's copyrights.
* DO NOT REDISTRIBUTE GAME ASSETS OR PROMOTE PIRACY.
*
* AI USE GUIDELINES:
* This project is built with minimal AI usage. We may utilize basic inline code 
* suggestions or rely on AI assistance for debugging, but the vast majority of 
* this codebase is written by hand. We manually decompile functions,
* reverse engineer structs, and write hooks to ensure accuracy and maintainability.
*
* The core goal of ReTiP is not only to get the game running, but to 
* research, document, and learn exactly how the game operates under the hood so that 
* we can provide modding support. We do not support using AI for creative 
* task or problem solving. i.e asking an AI agent to "find a way to 
* make freecam work". Instead, AI should only be used for small, boilerplate tasks or
* parsing a 1000 line crash log to isolate an error. We actively encourage all project 
* contributors to avoid the use of AI agents entirely when writing code or decompiling functions.
*
* The truth of the matter is that AI when used currectly by people who understand the output
* can be incredibly useful just like intelisense, being able to press Tab to autocomplete a
* for loop can save time. However, AI is not a replacement for human understanding and
* should not be used to replace the process of learning and understanding how the game works.
*
* We strongly prefer the use of local models that do not harm the environment and 
* can run entirely on your own local hardware over cloud based AI services. Ultimately, 
* all pull requests and code contributions will be strictly reviewed by people who 
* understand the codebase and the game. If you list Claude or any other AI as a coauthor 
* or contributor, your PR will be rejected regardless of whether it works.
******************************************************************************
*/

#include "TiPTools.h"
#include "imgui.h"
#include "SmartStyles.h"
#include "TiPWidgets.h"
#include "TiPTools/CvarMenu.h"
#include "tip_engine/Globals.h"
#include <rex/cvar.h>

#include <algorithm>
#include <string_view>

#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>
#endif

static constexpr float kMenuWidth = 220.0f;
static constexpr float kSubPanelWidth = 320.0f;
static constexpr float kMenuPadding = 2.0f;
static constexpr float kItemHeight = 32.0f;
static constexpr float kHeaderHeight = 38.0f;
static constexpr float kWarningHeight = 18.0f;
static constexpr float kSaveFeedbackTime = 2.0f;

static constexpr std::string_view kCvarPagePrefix = "TiP/";

static bool IsAltUnlockHeld(const ImGuiIO& io) {
#ifdef _WIN32
    return (GetAsyncKeyState(VK_MENU) & 0x8000) != 0;
#else
    if (io.KeyAlt || ImGui::IsKeyDown(ImGuiKey_LeftAlt) || ImGui::IsKeyDown(ImGuiKey_RightAlt)) {
        return true;
    }
    return false;
#endif
}

void TipToolsDialog::SaveSettings() {
    rex::cvar::SaveConfig(configPath_);
    lastSaveTime = (float)ImGui::GetTime();
}

void TipToolsDialog::SyncCvarPages() {
    if (selectedPage >= 0) return;

    const auto& registry = rex::cvar::GetRegistry();
    if (registry.size() == lastRegistrySize_) return;
    lastRegistrySize_ = registry.size();

    std::vector<std::string> wanted;
    for (const auto& entry : registry) {
        if (entry.is_debug_only) continue;
        const std::string_view category = entry.category;
        if (!category.starts_with(kCvarPagePrefix) || category.size() == kCvarPagePrefix.size()) {
            continue;
        }
        if (std::find(wanted.begin(), wanted.end(), entry.category) == wanted.end()) {
            wanted.push_back(entry.category);
        }
    }

    for (const auto& page : pages) {
        if (page->autoGenerated || page->cvarCategory.empty()) continue;
        wanted.erase(std::remove(wanted.begin(), wanted.end(), page->cvarCategory), wanted.end());
    }

    pages.erase(std::remove_if(pages.begin(), pages.end(), [&](const auto& page) {
        return page->autoGenerated &&
               std::find(wanted.begin(), wanted.end(), page->cvarCategory) == wanted.end();
    }), pages.end());

    for (const auto& category : wanted) {
        const bool exists = std::any_of(pages.begin(), pages.end(),
            [&](const auto& page) { return page->cvarCategory == category; });
        if (!exists) {
            pages.push_back(std::make_unique<CvarMenuPage>(category));
        }
    }

    std::stable_sort(pages.begin(), pages.end(), [](const auto& a, const auto& b) {
        if (a->autoGenerated != b->autoGenerated) return b->autoGenerated;
        if (a->autoGenerated) return a->name < b->name;
        return false;
    });
}

void TipToolsDialog::HandleInput() {
    if (selectedPage >= 0) return;

    auto input = TiPWidgets::PollInput(lastInputTime, 0.18f);

    int pageCount = static_cast<int>(pages.size());
    int itemCount = pageCount + 1;
    if (itemCount <= 0) return;
    if (highlightedIndex >= itemCount) highlightedIndex = itemCount - 1;

    int vertDir = TiPWidgets::GetHeldDir(SDL_GAMEPAD_BUTTON_DPAD_UP, SDL_GAMEPAD_BUTTON_DPAD_DOWN, ImGuiKey_UpArrow, ImGuiKey_DownArrow);
    int vertDelta = TiPWidgets::AccelTick(vertAccel, vertDir, 15.0f, 1.0f);

    if (vertDelta != 0) {
        highlightedIndex = ((highlightedIndex + vertDelta) % itemCount + itemCount) % itemCount;
    }

    if (input.confirm) {
        if (highlightedIndex == pageCount) {
            SaveSettings();
            TiPWidgets::SetInputCooldown(0.25f);
            return;
        }

        selectedPage = highlightedIndex;
        pages[selectedPage]->OnOpen();
        TiPWidgets::SetInputCooldown(0.25f);
    }

    if (input.back) {
        visible_ = false;
        TiPWidgets::SetInputCooldown(0.25f);
    }
}

void TipToolsDialog::DrawMenu() {
    SyncCvarPages();
    HandleInput();
    SetUIColor(ImColor(0, 255, 150));

    ImGuiWindowFlags menuFlags = ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoNav;

    float totalHeight = kHeaderHeight + kWarningHeight + (kItemHeight * (pages.size() + 1));
    ImGui::SetNextWindowSize(ImVec2(kMenuWidth, totalHeight), ImGuiCond_Always);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
    ImGui::Begin("TiP Tools###TiPMainMenu", nullptr, menuFlags);
    ImGui::PopStyleVar();

    {
        ImVec2 winPos = ImGui::GetWindowPos();
        ImVec2 headerMin = ImVec2(winPos.x, winPos.y);
        ImVec2 headerMax = ImVec2(winPos.x + kMenuWidth, winPos.y + kHeaderHeight);

        ImGui::GetWindowDrawList()->AddRectFilled(headerMin, headerMax, ImColor(0, 200, 120, 255));

        {
            const char* xLabel = "X";
            ImVec2 xSize = ImGui::CalcTextSize(xLabel);
            float xPad = 6.0f;
            ImVec2 xBtnMin = ImVec2(headerMax.x - xSize.x - xPad * 2.0f, headerMin.y + 2.0f);
            ImVec2 xBtnMax = ImVec2(headerMax.x - 2.0f, headerMin.y + kHeaderHeight - 2.0f);
            ImVec2 xTextPos = ImVec2(
                xBtnMin.x + ((xBtnMax.x - xBtnMin.x) - xSize.x) * 0.5f,
                xBtnMin.y + ((xBtnMax.y - xBtnMin.y) - xSize.y) * 0.5f
            );

            bool xHovered = ImGui::IsMouseHoveringRect(xBtnMin, xBtnMax);
            ImU32 xBg = xHovered ? ImColor(200, 50, 50, 255) : ImColor(0, 160, 100, 255);
            ImGui::GetWindowDrawList()->AddRectFilled(xBtnMin, xBtnMax, xBg, 4.0f);
            ImGui::GetWindowDrawList()->AddText(xTextPos, ImColor(255, 255, 255, 255), xLabel);

            if (xHovered && ImGui::IsMouseClicked(0)) {
                visible_ = false;
            }
        }

        const char* title = "ReTiP Menu";
        ImVec2 textSize = ImGui::CalcTextSize(title);
        ImVec2 textPos = ImVec2(
            headerMin.x + (kMenuWidth - textSize.x) * 0.5f,
            headerMin.y + (kHeaderHeight - textSize.y) * 0.5f
        );
        ImGui::GetWindowDrawList()->AddText(textPos, ImColor(255, 255, 255, 255), title);

        ImGui::SetCursorPosY(kHeaderHeight);
        ImGui::SetCursorPosX(0);
    }

    {
        ImVec2 winPos = ImGui::GetWindowPos();
        ImVec2 warnMin = ImVec2(winPos.x, winPos.y + kHeaderHeight);
        ImVec2 warnMax = ImVec2(winPos.x + kMenuWidth, winPos.y + kHeaderHeight + kWarningHeight);
        ImGui::GetWindowDrawList()->AddRectFilled(warnMin, warnMax, ImColor(180, 120, 0, 220));
        const char* warnText = "Experimental - Use at your own risk";
        ImVec2 warnTextSize = ImGui::CalcTextSize(warnText);
        ImVec2 warnTextPos = ImVec2(
            warnMin.x + (kMenuWidth - warnTextSize.x) * 0.5f,
            warnMin.y + (kWarningHeight - warnTextSize.y) * 0.5f
        );
        ImGui::GetWindowDrawList()->AddText(warnTextPos, ImColor(255, 230, 150, 255), warnText);
        ImGui::SetCursorPosY(kHeaderHeight + kWarningHeight);
        ImGui::SetCursorPosX(0);
    }

    TiPWidgets::PushListStyle();

    for (size_t i = 0; i < pages.size(); i++) {
        bool isSelected = (selectedPage == static_cast<int>(i));
        bool isHighlighted = (highlightedIndex == static_cast<int>(i));

        if (TiPWidgets::ListButton(pages[i]->name.c_str(), isHighlighted, isSelected, kMenuWidth, kItemHeight, true)) {
            highlightedIndex = static_cast<int>(i);
            if (isSelected) {
                pages[i]->OnClose();
                selectedPage = -1;
            } else {
                if (selectedPage >= 0 && selectedPage < static_cast<int>(pages.size()))
                    pages[selectedPage]->OnClose();
                selectedPage = static_cast<int>(i);
                pages[i]->OnOpen();
            }
        }

        if (ImGui::IsItemHovered()) {
            highlightedIndex = static_cast<int>(i);
            ImGui::SetTooltip("%s", pages[i]->description.c_str());
        }
    }

    int saveIndex = static_cast<int>(pages.size());
    bool saveHighlighted = (highlightedIndex == saveIndex && selectedPage < 0);
    bool savedRecently = lastSaveTime >= 0.0f &&
        ((float)ImGui::GetTime() - lastSaveTime) < kSaveFeedbackTime;
    const char* saveLabel = savedRecently ? "Saved TiPTools Settings" : "Save TiPTools Settings";
    if (TiPWidgets::ListButton(saveLabel, saveHighlighted, false, kMenuWidth, kItemHeight, false)) {
        highlightedIndex = saveIndex;
        SaveSettings();
    }

    if (ImGui::IsItemHovered()) {
        highlightedIndex = saveIndex;
        ImGui::SetTooltip("Save modified settings to %s", configPath_.filename().string().c_str());
    }

    TiPWidgets::PopListStyle();

    ImVec2 menuPos = ImGui::GetWindowPos();
    ImGui::End();
    PopUIColor();

    if (selectedPage >= 0 && selectedPage < static_cast<int>(pages.size())) {
        SetUIColor(pages[selectedPage]->color);

        ImGui::SetNextWindowPos(ImVec2(menuPos.x + kMenuWidth + kMenuPadding, menuPos.y), ImGuiCond_Always);
        ImGui::SetNextWindowSize(ImVec2(kSubPanelWidth, 0), ImGuiCond_Always);

        std::string panelTitle = pages[selectedPage]->name + "###TiPSubPanel";
        bool subPanelOpen = true;
        ImGui::Begin(panelTitle.c_str(), &subPanelOpen, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoMove);

        pages[selectedPage]->OnDraw();

        ImGui::End();
        PopUIColor();

        if (!subPanelOpen || pages[selectedPage]->wantsClose) {
            pages[selectedPage]->wantsClose = false;
            pages[selectedPage]->OnClose();
            selectedPage = -1;
            TiPWidgets::SetInputCooldown(0.25f);
        }
    }
}

void TipToolsDialog::OnDraw(ImGuiIO& io) {
    static float selectHoldStart = -1.0f;
    static constexpr float kHoldThreshold = 0.5f;
    float now = (float)ImGui::GetTime();

    bool selectDown = TiPWidgets::IsSelectPressed();

    if (!visible_) {
        if (selectDown) {
            if (selectHoldStart < 0.0f)
                selectHoldStart = now;
            else if (now - selectHoldStart >= kHoldThreshold) {
                visible_ = true;
                selectHoldStart = -1.0f;
                TiPWidgets::SetInputCooldown(0.3f);
            }
        } else {
            selectHoldStart = -1.0f;
        }
    } else {
        selectHoldStart = -1.0f;
    }

    g_RetipOwnUiMode = visible_ || g_LaunchMenuOpen || g_QuitConfirmActive || g_StarMenuOpen ||
                       IsAltUnlockHeld(io);
    SetRetipInputUiMode(g_RetipOwnUiMode || IsRexOverlayOpen());

    if (!visible_) {
        return;
    }
    DrawMenu();
}
